name: "CI Check"

on: [pull_request, push]

jobs:
  ci:
    name: "CI Check"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
